import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((e) => (
          <a key={e.id} href={`/events/${e.id}`}>
            <Image width={300} height={300} alt={e.title} src={e.image} />
            <h2>{e.title}</h2>
            <a>{e.description}</a>
          </a>
        ))}
      </main>

      <footer className={styles.footer}>
        <p>2022 Time To Code - A Project Next js</p>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");

  console.log(events_categories);
  return {
    props: {
      data: events_categories,
    },
  };
}
